language: node_js
os:
  - linux
  - osx
addons:
  ssh_known_hosts:
    - github.com 
before_script:
node_js:
  - 6
  - 8
  - 10
install:
  - npm install bigcommerce-labs/node-sass#support_node10 
  - npm install --production
script:
